openapi: 3.0.1
info:
  title: Payment & Subscription API
  description: Public documentation for payment & subscription System
  contact:
    email: ourteam@subs.com
  version: 1.0.0
servers:
  - url: https://api.payments.com/
paths:
  /users:
    get:
      summary: Return details about users
      operationId: getUsers
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: bad request
          content: {}
        404:
          description: users not found
          content: {}
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      required:
        - id
        - username
        - email
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        subscriptionStatus:
          type: boolean
        subscriptionType:
          type: string
        email:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
